import Image from "next/image";
import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main className="min-h-screen p-24">

    </main>
  );
}
